Repository modelcontextprotocol/servers, pull requests merged in 2025-05, with the labels that each got.

#1174 Add Alibaba Cloud AnalyticDB for MySQL MCP Server to README
  README.md
Labels: add-official-server

#1183 Fix docker warnings in Puppeteer dockerfile
  src/puppeteer/Dockerfile
Labels: bug, server-puppeteer

#1201 Add a Puppeteer tool to capture screenshot as raw base64 text
  src/puppeteer/README.md
  src/puppeteer/index.ts
Labels: enhancement, server-puppeteer

#1491 Add Apache Gravitino
  README.md
Labels: add-community-server

#1010 Add Plane MCP
  README.md
Labels: add-community-server, waiting for submitter

#1024 Add ITerm2 Terminal MCP Server to Community Servers List
  README.md
Labels: add-community-server

#1021 Add Email MCP Server to list of community servers
  README.md
Labels: add-community-server

#1054 Added Ableton MCP to server
  README.md
Labels: add-community-server

#1053 Add Office-Word-MCP-Server
  README.md
Labels: add-community-server

#1051 Add GitHub Enterprise MCP community server integration
  README.md
Labels: add-community-server

#1168 Add Morningstar MCP Server
  README.md
Labels: add-official-server

#986 Add 10 crypto-related mcp servers
  README.md
Labels: add-community-server, waiting for submitter

#1084 Update README.md to add Gitea MCP
  README.md
Labels: add-official-server, waiting for submitter

#1028 Add Linear
  README.md
Labels: add-community-server

#1162 Add Edgee MCP server to the official integration list
  README.md
Labels: add-official-server, waiting for submitter

#1109 Add Video Still Capture MCP to README
  README.md
Labels: add-community-server

#1025 Add official Honeycomb Enterprise MCP Server
  README.md
Labels: add-official-server

#988 Update README.md with Glean MCP server
  README.md
Labels: add-official-server, waiting for submitter

#1072 Add lldb-mcp to README.md
  README.md
Labels: add-community-server, waiting for submitter

#1750 Add Federal Reserve Economic Data MCP Server
  README.md
Labels: add-community-server, waiting for submitter

#1111 Update README.md add Prefect implementation
  README.md
Labels: add-community-server, waiting for submitter

#1119 feat: MCP server for lark(Feishu)
  README.md
Labels: add-community-server, waiting for submitter

#1139 Add Salesforce MCP
  README.md
Labels: add-community-server, waiting for submitter

#1148 Add WhatsApp MCP server
  README.md
Labels: add-community-server

#1167 docs: add tianji mcp server link
  README.md
Labels: add-official-server

#1169 Add Edwin to MCP server list
  README.md
Labels: add-community-server

#1164 Add Multi-Model Advisor to the list of community MCP servers in README
  README.md
Labels: add-community-server

#1462 Add ntfy-me-mcp server
  README.md
Labels: add-community-server

#1177 Integrate the MCP Server for Mifos X an Open Source Core Banking Solu…
  README.md
Labels: add-community-server, waiting for submitter

#1181 Add Spring AI MCP Client and Server to README.md
  README.md
Labels: documentation

#1186 Add DataWorks for the MCP Server
  README.md
Labels: add-community-server

#1152 Update README.md to add a new Community Server (Shodan)
  README.md
Labels: add-community-server, waiting for submitter

#1747 Adding Microsoft Clarity MCP
  README.md
Labels: add-community-server, waiting for submitter

#1196 Add official Upstash MCP server to README
  README.md
Labels: add-official-server

#1230 Add official Burp Suite MCP server extension to servers list
  README.md
Labels: add-official-server

#1316 Added Confluent MCP server project
  README.md
Labels: add-official-server

#1269 add OP.GG to list of official integrations
  README.md
Labels: add-official-server

#1170 docs: add Jupyter Notebook MCP to Community Servers
  README.md
Labels: add-community-server, waiting for submitter

#1255 Add Pulumi to Official Integrations README.md
  README.md
Labels: add-official-server, waiting for submitter

#1071 docs: add lottiefiles
  README.md
Labels: add-community-server

#1419 Add the official Grafbase MCP server
  README.md
Labels: add-official-server

#1234 [Docs] Add link to official Root Signals MCP github to Readme
  README.md
Labels: add-official-server, waiting for submitter

#1117 Add Verbwire MCP Server to official integrations list
  README.md
Labels: add-official-server

#1194 update readme: added official dexpaprika mcp server
  README.md
Labels: add-official-server

#1238 Add WayStation server to README
  README.md
Labels: add-official-server

#1333 chore: add tl;dv into the Official Integrations
  README.md
Labels: add-official-server

#1466 Add Official KWDB integration for MCP
  README.md
Labels: add-official-server, waiting for submitter

#1318 Add official Put.io MCP server
  README.md
Labels: add-official-server

#1136 Add Xcode MCP Server to community servers list
  README.md
Labels: add-community-server, waiting for submitter

#1182 Add containerd mcp server
  README.md
Labels: add-community-server, waiting for submitter

#1195 Add pure.md MCP server to README
  README.md
Labels: add-community-server, waiting for submitter

#1193 Add Matlab-MCP server
  README.md
Labels: add-community-server, waiting for submitter

#1091 Update README to include MasterGo MCP
  README.md
Labels: add-community-server, waiting for submitter

#1271 docs: add Standard Korean Dictionary MCP server to the README
  README.md
Labels: add-community-server
