Repository modelcontextprotocol/servers, pull requests merged in 2025-06, with the labels that each got.

#2006 add LaunchDarkly MCP server to README
  README.md
Labels: add-official-server

#2010 add alibabacloud opensearch mcp server in README
  README.md
Labels: add-official-server

#2007 Add 124 Community MCP Servers
  README.md
Labels: add-community-server

#2075 Add 63 Official MCP Integrations
  README.md
Labels: add-official-server

#1027 Add head/tail file reading and directory size listings to filesystem server
  src/filesystem/index.ts
Labels: enhancement, server-filesystem

#2053 Add SAP ABAP MCP Server SDK to "For Servers" within "Frameworks"
  README.md
Labels: add-community-resource

#1133 Fix json format
  src/git/README.md
Labels: documentation, server-git

#1495 Add ActionKit to third-party servers list
  README.md
Labels: add-official-server

#1919 Add instructions to Everything Server
  src/everything/everything.ts
  src/everything/instructions.md
  src/everything/package.json
Labels: enhancement, server-everything

#1405 Add path utils and test config for filesystem
  .github/workflows/typescript.yml
  package-lock.json
  src/filesystem/__tests__/path-utils.test.ts
  src/filesystem/jest.config.cjs
  src/filesystem/package.json
  src/filesystem/path-utils.ts
Labels: enhancement, server-filesystem

#1753 [FIX] `mcp_server_git`: replace deprecated pydantic functions and small fixes to typing issues
  src/git/pyproject.toml
  src/git/src/mcp_server_git/py.typed
  src/git/src/mcp_server_git/server.py
Labels: server-git

#1326 feat(mcp-server-git): Add context_lines to git_diff* tools
  src/git/README.md
  src/git/src/mcp_server_git/server.py
Labels: enhancement, server-git

#1943 Add Git Branch tool to mcp-server-git
  src/git/README.md
  src/git/src/mcp_server_git/server.py
  src/git/tests/test_server.py
Labels: enhancement, server-git

#2031 Added MCP-Plexus multi-tenant python framework
  README.md
Labels: add-community-resource

#1421 Update README.md to include Foobara framework's mcp-connector
  README.md
Labels: add-community-resource

#1415 Update README.md to add high-level framework mcp-declarative-java-sdk
  README.md
Labels: add-community-resource

#1044 Adding MCP-Agent to the README.md
  README.md
Labels: add-community-resource
