Repository modelcontextprotocol/servers, pull requests merged in 2025-04, with the labels that each got.

#770 Update README.md to add community browser-use MCP server
  README.md
Labels: add-community-server

#983 Add Baidu Cloud AISearch MCPServer to community server list
  README.md
Labels: add-community-server

#1057 Add official BICScan MCP server to README.md
  README.md
Labels: add-official-server

#1166 Add missing capabilities and improve connection handling for server-redis
  src/redis/README.md
  src/redis/src/index.ts
Labels: bug, server-redis

#1061 Add official Elasticsearch MCP server to README
  README.md
Labels: add-official-server

#1095 Add Paddle MCP server to official integrations
  README.md
Labels: add-official-server

#1127 [community mcp] add attestable-mcp
  README.md
Labels: add-community-server

#1132 Add chess.com mcp
  README.md
Labels: add-community-server

#1090 Update README to include Astra DB MCP server
  README.md
Labels: add-official-server

#1426 Standardize build and binary references for server-redis
  package-lock.json
  src/redis/README.md
  src/redis/package.json
  src/redis/src/index.ts
  src/redis/tsconfig.json
Labels: bug, server-redis

#1488 [slack] Instruct users to add users.profile:read scope to token
  src/slack/README.md
Labels: documentation, server-slack

#1449 update sqlite's mcp version to 1.6.0
  src/sqlite/README.md
  src/sqlite/pyproject.toml
  src/sqlite/src/mcp_server_sqlite/server.py
  src/sqlite/test.db
  src/sqlite/uv.lock
Labels: enhancement, server-sqlite

#1427 Update incorrect Brave Search developer dashboard URL
  src/brave-search/README.md
Labels: documentation, server-brave-search

#1282 fix: Add completions capability to Everything server
  src/everything/everything.ts
Labels: enhancement, server-everything

#1392 Add Atlan MCP
  README.md
Labels: add-official-server

#1492 add mcp_weather mcp github link
  README.md
Labels: add-community-server

#1335 fix: use default HEAD as ref
  src/gitlab/index.ts
Labels: bug, server-gitlab

#1437 Update README.md
  README.md
Labels: add-official-server

#1328 Add MCP Toolbox for Databases to readme
  README.md
Labels: add-community-server

#1478 Add GibsonAI MCP
  README.md
Labels: add-community-server

#637 Add a link community MCP server for Google Cloud Vertex AI Search
  README.md
Labels: add-community-server

#732 [community servers] Add geropl/git-mcp-go
  README.md
Labels: add-community-server

#698 Add my servers DPLP and Solver to README.md
  README.md
Labels: add-community-server

#1366 Add Strava MCP server to community servers list
  README.md
Labels: add-community-server

#1008 Add ClickUp MCP Server to Community Servers
  README.md
Labels: add-community-server

#1019 Add mcp server: Computer-Use - Remote MacOS Use
  README.md
Labels: add-community-server

#1512 Add consul and nomad mcp to community servers
  README.md
Labels: add-community-server, waiting for submitter

#1017 Adding Deep Research MCP server
  README.md
Labels: add-community-server

#990 Add community opensource server: Google Sheets Access/Edit
  README.md
Labels: add-community-server

#987 Add CoinMarketCap server for complete API access
  README.md
Labels: add-community-server

#989 Update README.md with Createve.AI Nexus Server
  README.md
Labels: add-community-server

#1357 Add prisma server
  README.md
Labels: add-community-server, waiting for submitter

#1094 add community server Applescript-mcp
  README.md
Labels: add-community-server, waiting for submitter

#1391 Proposal to add community MCP Slack server to the README
  README.md
Labels: add-community-server

#1486 add Arize Phoenix integration to readme
  README.md
Labels: add-community-server

#1496 add streamableHttp server support for everything server
  package-lock.json
  src/everything/README.md
  src/everything/package.json
  src/everything/streamableHttp.ts
Labels: enhancement, server-everything

#1070 add new pubchem mcp server in readme for community part
  README.md
Labels: add-community-server, waiting for submitter

#1011 Add Outline MCP Server to list of community servers
  README.md
Labels: add-community-server

#1022 Add Talk To Figma MCP to README
  README.md
Labels: add-community-server

#1013 Add DaVinci Resolve MCP server to community servers list
  README.md
Labels: add-community-server, waiting for submitter

#1390 PR to add MalwareBazaar_MCP server to the Community list.
  README.md
Labels: add-community-server
