Repository modelcontextprotocol/servers, pull requests merged in 2025-07, with the labels that each got.

#2267 Simple README.md typo fix for the memory server
  src/memory/README.md
Labels: documentation

#2215 Example showing how to use elicitation
  src/everything/README.md
  src/everything/everything.ts
Labels: enhancement, server-everything

#2185 Adding Teradata to the Official Integrations list, this is to replace…
  README.md
Labels: add-official-server

#2352 Add Go SDK to README.md
  README.md
Labels: documentation

#2187 Added TigerGraph to community server list
  README.md
Labels: add-community-server

#2009 Add Browser Use MCP with vision
  README.md
Labels: add-community-server

#2327 Add a streamlined mcp client
  README.md
Labels: add-community-resource

#2329 Add MCP-Hunt.com to community resources list
  README.md
Labels: add-community-resource

#2331 Add ModelFetch to Frameworks for MCP Servers
  README.md
Labels: add-community-resource

#2302 Add AutoML server to community server list
  README.md
Labels: add-community-server

#2299 Add GoLogin MCP Server
  README.md
Labels: add-official-server

#2288 add: Orshot MCP Server
  README.md
Labels: add-community-server

#2265 chore: add hermes-mcp
  README.md
Labels: add-community-resource

#2259 Add Alby Bitcoin Payment MCP server
  README.md
Labels: add-official-server

#2047 Update README.md
  README.md
Labels: add-official-server, waiting for submitter

#1975 GMAILMCP
  README.md
Labels: add-community-server, waiting for submitter

#1898 Add FIXParser MCP Server Official Integration
  README.md
Labels: add-official-server

#1728 Update README.md to add agentmode
  README.md
Labels: add-community-server

#2257 Update README.md
  README.md
Labels: add-community-server, waiting for submitter

#2330 docs: Add SystemSage to community servers list
  README.md
Labels: add-community-server, waiting for submitter

#1461 Add Adobe Commerce Community MCP server
  README.md
Labels: add-community-server, waiting for submitter

#2435 Update src/filesystem/README.md
  src/filesystem/README.md
Labels: bug, documentation

#2396 Removing Duplicate Memgraph entry
  README.md
Labels: documentation, waiting for submitter

#2272 [everything] Add structured content tool
  src/everything/README.md
  src/everything/everything.ts
  src/everything/instructions.md
Labels: enhancement, server-everything
