Repository modelcontextprotocol/servers, pull requests merged in 2025-08, with the labels that each got.

#2467 Add comprehensive tests for get_local_tz timezone detection
  src/time/test/time_server_test.py
Labels: enhancement, server-time

#1276 calling [mcp/memory] read_graph without args
  src/memory/README.md
  src/memory/index.ts
Labels: bug, server-memory

#2445 Adding PHP-MCP client and server
  README.md
Labels: add-community-resource

#2448 Add PayMCP to Frameworks → For servers
  README.md
Labels: add-community-resource

#2489 Add Perl SDK
  README.md
Labels: waiting for submitter, add-community-resource

#2442 Add link to official Brave Search server
  README.md
Labels: add-official-server

#2328 docs: Update VS Code installation instructions to use mcp.json for issue #2320
  src/everything/README.md
  src/filesystem/README.md
  src/git/README.md
  src/memory/README.md
  src/sequentialthinking/README.md
Labels: documentation

#1635 Update README.md
  README.md
Labels: add-official-server

#1675 Add Squad MCP
  README.md
Labels: add-community-server

#2503 Add support for git-lfs
  src/git/Dockerfile
Labels: documentation, server-git

#2282 Add Baserow to MCP servers
  README.md
Labels: add-official-server, waiting for submitter

#2306 Add Cloudbet Sports MCP Server
  README.md
Labels: add-official-server

#2350 Keywords everywhere mcp server
  README.md
Labels: add-official-server

#2380 Add Kernel MCP integration to README
  README.md
Labels: add-official-server

#2363 Include parliament-mcp in servers list
  README.md
Labels: add-community-server

#2385 Add Wordle MCP server and standardize note formatting
  README.md
Labels: add-community-server

#1899 Update README.md with addition of mcp-EDA
  README.md
Labels: add-community-server, waiting for submitter

#2196 Add mxcp
  README.md
Labels: waiting for submitter, add-community-resource

#2508 Update README.md
  README.md
Labels: add-community-server

#2436 upd: Add Blockbench MCP to README
  README.md
Labels: add-community-server

#2474 Add NPM Plus MCP Server to community servers
  README.md
Labels: add-community-server

#2502 Added ProdE MCP in readme
  README.md
Labels: add-official-server

#2535 add Paubox MCP server
  README.md
Labels: add-official-server

#2566 fix: remove incorrect resources claim from filesystem server README
  src/filesystem/README.md
Labels: documentation, server-filesystem

#2569 Fix SSE server crash by starting notification timers only after client connects
  src/everything/everything.ts
  src/everything/sse.ts
Labels: bug, server-everything

#2571 fix: clarify list_allowed_directories description to mention subdirectory access
  src/filesystem/index.ts
Labels: enhancement, server-filesystem

#2057 feat(git): add date-based commit log retrieval functions
  src/git/README.md
  src/git/src/mcp_server_git/server.py
Labels: enhancement, server-git

#2607 refactor(CONTRIBUTING.md): streamline contribution guidelines and improve clarity
  CONTRIBUTING.md
Labels: documentation
